// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlq_IMB8RzggMXABz-bcigTW1AoqG8GOE',
    appId: '1:1016347653502:web:63ff317a7ab88c79aaef2f',
    messagingSenderId: '1016347653502',
    projectId: 'al-ukhuwah',
    authDomain: 'al-ukhuwah.firebaseapp.com',
    storageBucket: 'al-ukhuwah.appspot.com',
    measurementId: 'G-4HYN0ZHZXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyxA6v8e8Q9ZSNhuzq_kVl4awah8pP-6Q',
    appId: '1:1016347653502:android:1a1b815288240108aaef2f',
    messagingSenderId: '1016347653502',
    projectId: 'al-ukhuwah',
    storageBucket: 'al-ukhuwah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW5xtcR4X3_QoVPN0hITaVUff4oN36FJw',
    appId: '1:1016347653502:ios:0b8bbd56aa7a5940aaef2f',
    messagingSenderId: '1016347653502',
    projectId: 'al-ukhuwah',
    storageBucket: 'al-ukhuwah.appspot.com',
    androidClientId: '1016347653502-ur1p7vvqvv751j4oq2l5vhu8l8patuq0.apps.googleusercontent.com',
    iosBundleId: 'com.muslimdeveloper.alUkhuwah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW5xtcR4X3_QoVPN0hITaVUff4oN36FJw',
    appId: '1:1016347653502:ios:0b8bbd56aa7a5940aaef2f',
    messagingSenderId: '1016347653502',
    projectId: 'al-ukhuwah',
    storageBucket: 'al-ukhuwah.appspot.com',
    androidClientId: '1016347653502-ur1p7vvqvv751j4oq2l5vhu8l8patuq0.apps.googleusercontent.com',
    iosBundleId: 'com.muslimdeveloper.alUkhuwah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlq_IMB8RzggMXABz-bcigTW1AoqG8GOE',
    appId: '1:1016347653502:web:d0f5cb0559477366aaef2f',
    messagingSenderId: '1016347653502',
    projectId: 'al-ukhuwah',
    authDomain: 'al-ukhuwah.firebaseapp.com',
    storageBucket: 'al-ukhuwah.appspot.com',
    measurementId: 'G-BLL9274RPR',
  );

}