// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // BELUM DIPERBAIKI: web/iOS/macOS masih menunjuk `al-ukhuwah`.
  //
  // Berbeda dengan Android, TIDAK ada bukti bahwa aplikasi web/iOS sudah
  // terdaftar di project `syathiby-1345121` -- google-services.json hanya
  // memuat entri Android. Menebak appId/apiKey akan membuat Firebase gagal
  // inisialisasi, jadi sengaja dibiarkan sampai pendaftarannya dipastikan.
  //
  // Dampaknya terbatas: push untuk staff dikirim ke perangkat Android, dan
  // `al-ukhuwah` sendiri masih hidup (hanya bukan milik pondok) sehingga
  // Firebase.initializeApp di web tetap berhasil dan aplikasi web tidak rusak.
  // Yang tidak jalan hanya push ke browser.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlq_IMB8RzggMXABz-bcigTW1AoqG8GOE',
    appId: '1:1016347653502:web:63ff317a7ab88c79aaef2f',
    messagingSenderId: '1016347653502',
    projectId: 'al-ukhuwah',
    authDomain: 'al-ukhuwah.firebaseapp.com',
    storageBucket: 'al-ukhuwah.appspot.com',
    measurementId: 'G-4HYN0ZHZXG',
  );

  // Diperbaiki 8 Sep 2026 -- sebelumnya menunjuk project `al-ukhuwah`.
  //
  // `al-ukhuwah` adalah project LAMA sebelum rebranding dan sudah tidak ada
  // hubungannya dengan aplikasi Syathiby sekarang; akun Google pondok bahkan
  // tidak punya akses ke sana. Akibatnya token FCM yang didaftarkan aplikasi
  // staff tidak pernah bisa dikirimi notifikasi oleh backend.
  //
  // Dibuktikan 8 Sep 2026 lewat FCM v1 dry-run (`validate_only`) dari server
  // produksi memakai service account project `syathiby-1345121`:
  //     token staff 083814740637 -> HTTP 403 SENDER_ID_MISMATCH
  // Artinya token itu memang diterbitkan project LAIN.
  //
  // Package `id.syathiby.app` TERNYATA SUDAH TERDAFTAR di project yang benar --
  // terlihat di apps/flutter_syathiby_walsan/android/app/google-services.json
  // yang memuat entri untuk `id.syathiby.app` DAN `id.syathiby.walsan`. Jadi
  // tidak perlu mendaftarkan aplikasi baru, cukup diarahkan ke sana.
  //
  // CATATAN: token lama tidak otomatis berpindah. Setiap staff harus memakai
  // APK/web build baru dan login ulang supaya tokennya terdaftar di project
  // yang benar.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAML43jqvWkDzw7WtH5FXxDPaNQmJGbr6w',
    appId: '1:921923279470:android:46c097ead14640fbb8247f',
    messagingSenderId: '921923279470',
    projectId: 'syathiby-1345121',
    storageBucket: 'syathiby-1345121.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW5xtcR4X3_QoVPN0hITaVUff4oN36FJw',
    appId: '1:1016347653502:ios:0b8bbd56aa7a5940aaef2f',
    messagingSenderId: '1016347653502',
    projectId: 'al-ukhuwah',
    storageBucket: 'al-ukhuwah.appspot.com',
    androidClientId: '1016347653502-ur1p7vvqvv751j4oq2l5vhu8l8patuq0.apps.googleusercontent.com',
    iosBundleId: 'com.muslimdeveloper.alUkhuwah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW5xtcR4X3_QoVPN0hITaVUff4oN36FJw',
    appId: '1:1016347653502:ios:0b8bbd56aa7a5940aaef2f',
    messagingSenderId: '1016347653502',
    projectId: 'al-ukhuwah',
    storageBucket: 'al-ukhuwah.appspot.com',
    androidClientId: '1016347653502-ur1p7vvqvv751j4oq2l5vhu8l8patuq0.apps.googleusercontent.com',
    iosBundleId: 'com.muslimdeveloper.alUkhuwah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlq_IMB8RzggMXABz-bcigTW1AoqG8GOE',
    appId: '1:1016347653502:web:d0f5cb0559477366aaef2f',
    messagingSenderId: '1016347653502',
    projectId: 'al-ukhuwah',
    authDomain: 'al-ukhuwah.firebaseapp.com',
    storageBucket: 'al-ukhuwah.appspot.com',
    measurementId: 'G-BLL9274RPR',
  );

}